### ISSUE TITLE
block excluded Ps from continuing

### ISSUE THREAD

**Issue by evmadden** [evmadden/SDCexp1#67]
We have our first instance of excluding a participant from the study due to poor performance in the immediate test.  Can we add a feature to enter their ID in an admin page (like the export page) in order to stop them from coming back for the delayed/follow-up tests?  At present, I can tell them they are no longer eligible but, in theory, they could come back and continue testing if they return to the original link I sent them at the beginning of the study.

**Comment by lancehilliard** [comment]
@evmadden 53d42cfb73d59b3f8c5955a1a49783ef727d49de adds enrollment activity status. In our Zoom call, we discussed using the Admin page to manage this, but I realized that activity is a property of _enrollment_, which we manage in ParticipantRecords.csv. To use this revision of the software (that is: to manage whether each participant is "Active" or not), you first must edit ParticipantRecords.csv, but... read the next paragraph first.

The first thing I want you to do, before you edit ParticipantRecords,csv, is to pull this revision of the code and run it, and then try to login as a participant. You'll get an "unexpected" error (**Figure A**). The only reason I want you to see this is so that you can associate your editing ParticipantRecords.csv with the error then being fixed. I just want you to lay eyeballs on how the "ParticipantRecords.csv is malformed" scenario affects the user experience, so that, if you see the same user experience again in the future, you might have an idea of where/how to _begin_ troubleshooting.

Before _successfully_ using this new revision of the software, you must (locally, and then in Azure, per site) add an "Active" column to ParticipantRecords.csv, wherein a row's mere _existence_ will continue to signify "Enrolled", and the new _boolean column_ will signify whether (1) or not (0) the participant is "Active". You must edit the file's first row to add the column header ("Active"), and then you must edit each row to add the appropriate value. Figure B provides example. Reminder, after you have tested locally: you then have to do this in Azure, before you deploy, per site.

Inactive Participants trying to login are told they are "Finished", and they are thanked for their time (**Figure C**).

Note, too, the ParticipantRecords.csv _Legend_ changes (**Figures D, E**), including my correction to the ID column's description.

Assigning to you for review and feedback.

---

![image](https://user-images.githubusercontent.com/278006/101379292-bb546280-3879-11eb-9b2f-cb1fc158a7df.png)
**&#8593;&#9608;&#8593; Figure A: Login User Experience given malformed ParticipantRecords.csv**

---

![image](https://user-images.githubusercontent.com/278006/101382634-cf01c800-387d-11eb-8c76-6c67b28b0a2b.png)
**&#8593;&#9608;&#8593; Figure B: Example ParticipantRecords.csv**

---

![image](https://user-images.githubusercontent.com/278006/101377826-f3f33c80-3877-11eb-9877-132f1c7f6db5.png)
**&#8593;&#9608;&#8593; Figure C: User Experience of Inactive Participant**

---

![image](https://user-images.githubusercontent.com/278006/101378172-6106d200-3878-11eb-8124-690006c91a29.png)
**&#8593;&#9608;&#8593; Figure D: Legend Before/Without Enrollment Activity Status**

---

![image](https://user-images.githubusercontent.com/278006/101378194-68c67680-3878-11eb-9a22-2cb8f3923c00.png)
**&#8593;&#9608;&#8593; Figure E: Legend After/With Enrollment Activity Status**

**Comment by evmadden** [comment]
Thanks for getting this done so quickly!  I've confirmed the unexpected error message when I haven't changed the .csv file.  However, when I changed the .csv on my local machine to include the new "Active" column and boolean logic, I'm still getting the unexpected error message.  You can see on the left that the .csv has been updated for a small number of the IDs and that I've tried to use one that should lead to the message that the test is finished, but that I'm still getting the error screen.
![Screenshot 2020-12-08 at 10 37 05 am](https://user-images.githubusercontent.com/69730899/101473107-53694f00-3941-11eb-8e82-ec4bf500e2f6.png)

**Comment by lancehilliard** [comment]
> you must edit each row to add the appropriate value

I think your experience is derived from your not yet having provided an appropriate "Active" value for _each_ row? Does that make sense given what you're seeing on your end? Does the "unexpected" error go away if you add "Active" values to _every_ row? If so, I'm sorry for being unclear before.

**Comment by evmadden** [comment]
After providing an appropriate value for all of the rows, I can confirm that this works now and looks great.  Closing this issue.
