### ISSUE TITLE
prevent access if English isn't native language

### ISSUE THREAD

**Issue by evmadden** [evmadden/SDCexp1#68]
As we are starting to get good data from our pilot study, we are also starting to find some interesting things coming out of the data.  

Today I discovered that the only way we have to catch a non-native English speaking participant is after they have completed the entire hour-long first session.  Even though we make it explicitly clear both on the platform where they sign up for the study and in several places on the website, we still had someone who does not speak English as their first language sign up and complete the first session.  Based on some of the data, this could be due to them not being fluent in English (I can explain this during an upcoming call due to this repository being public).  

Is it possible (and not too much trouble), since we have the demographics form before encoding, to have the system check that the user input for native language = English and, if it doesn't then they see a screen that says something about not being eligible to participate?  This will be crucial for the verbal version of the experiment where they are asked to remember target words in sentences.

**Comment by lancehilliard** [comment]
@evmadden ddce5779759227f99b6b860a6118b88f24baae32 prevents access beyond the Demographics form when the participant's native language is other than English. Please verify the following and provide feedback:

- any "Native Language" response beginning with "En" or "en" allows the participant to proceed
- any "Native Language" response not beginning with "En" or "en" halts the participant from proceeding
- any halted participant may begin again at the homepage and proceed until the language-check moment

That last point maybe isn't ideal. To be clear, the "demographics submission" moment is the only moment when the language is checked and the user is redirected. It's the "least change" approach. I can accept it if you can (maybe it's your _preference_). If you want to change the "language-disqualified participant tries again" user experience, let me know what you have in mind.

Here's a screenshot of what is shown in response to a disqualifying language input:

![image](https://user-images.githubusercontent.com/278006/101534807-5114ee00-395d-11eb-832f-367c3aebb3b6.png)

Assigning to you for review and feedback.

**Comment by evmadden** [comment]
@lancehilliard This looks and works great!  I changed the text slightly (plus a few other things with commit 389d33802b6f84942c32d5c28ef3a6124421cea8 ).
![Screenshot 2020-12-09 at 10 48 09 am](https://user-images.githubusercontent.com/69730899/101620152-1b7b0e00-3a0c-11eb-956c-618d4b440a1f.png)

I've tried a variety of inputs and the new update seems to be catching the issues.  I had a thought this morning that the new feature might throw out a participant that spells "English" wrong.  But given that it is basing it off the first 2 letters, that solved that problem and I was able to proceed even if it was spell incorrectly (but with the first two letters correct).  I also confirmed that it sends a participant to the finished screen if the language field is left blank.  But, I do like that it will allow them to re-enter the site and re-do it (for cases like this where they forget to enter something). 


I've also added an extra required box to the Consent Form page, further highlighting the language requirement.  I *think* I have added it to the csv file, but can you please check that I have done so correctly?
![Screenshot 2020-12-09 at 10 46 27 am](https://user-images.githubusercontent.com/69730899/101620256-38174600-3a0c-11eb-8531-53584ee0376c.png)

The last missing piece is for me to receive an email in situations where a participant fails the language check.  This will let me know to change their status to inactive and to possibly catch Ps who have re-entered and lied about their language.  I can treat their data with more caution.  Assigning back to you for feedback.

**Comment by lancehilliard** [comment]
@evmadden 3d95f19e059a858c77cfb88e1a982a449bdf2865 makes some Data Definition adjustments and, if notifications are enabled in the relevant appSettings, emails you when participants are disqualified due to language.

You added the checkbox to the HTML form successfully (great _jawwwb_), but a bit more code was required to save the value correctly into the data. I've taken care of that extra code.

In the CSV files you export _from now on_, you'll see that, for participants who submitted the Consent form _before we added this field_, the data shows _no AgreeLanguage value whatsoever_ (the _column_ is there, but the row's column _value_ is altogether empty - the corresponding form checkbox didn't _exist_ then). On the HTML form, the AgreeLanguage checkbox will always be a simple "yes or no" field (checked or not checked) -- those are the only two possibilities when the participant fills out the HTML form. But, in the _data_, which will _always_ include records captured before we _added_ this field, the possible values are "yes", "no", and "what the heck - that checkbox didn't even _exist_ when I participated!" -- so, in the CSV export, some participants will always show no AgreeLanguage value whatsoever.

Please test that the AgreeLanguage data is being correctly presented in new CSV exports. And do test that you receive an email when the participant is disqualified due to language (example Subject line: "42 Lang Disqual").

Assigning to you for review and feedback.

**Comment by evmadden** [comment]
@lancehilliard  I've pulled the code and tried to test it again.  I think I might be doing something wrong.  When I run the code locally, I'm not getting an email when the language doesn't match.  The 'finished' screen is correctly shown, but the email doesn't come through.  I'm also not quite sure where to find the csv files when I'm running the code locally :')  

Can we set up a call at some point today?  My new MacBook arrives shortly so will need to set up VSCode on the new machine anyway.

**Comment by lancehilliard** [comment]
I do have availability later today for a call. I'll send you some times.

In the interim, two ideas:

) are notifications enabled in your local appSettings.Development.json
file? I should have mentioned this consideration when I invited you to
test. Restart the web app to make it acknowledge any change you make.

) the CSV files are always downloadable via the /Export page, which creates
them anew each time, derived from known data at that moment.

**Comment by evmadden** [comment]
Confirm software is behaving properly during 11 December call.  Closing issue.
