### ISSUE TITLE
add audio to test sessions

### ISSUE THREAD

**Issue by evmadden** [evmadden/SDCexp1#74]
@lancehilliard I've tested the audio during encoding and all seems to be working fine as far as I can tell!  I made a few adjustments to the code where the wrong instructions were being shown and the visual images were being shown instead of the sentences.  That's all been pushed to the repository.  I still need to run the encoding session in full, but so far all is looking good.

We talked in a meeting today about whether the audio needs to play during the test sessions as well as the encoding session and the answer is yes.  It's best that we keep the design consistent (e.g., they see and hear the sentence when learning and they see and hear the sentence when being tested on it).  Looking at the average response time for the BSc experiment, participants are responding to the old/new choice after about 2.5s.  So, forcing them to listen to the entire 4s audio clip during a TEST SESSION might not be the best option.  Therefore, in the test sessions only, the software needs to behave in a way that stops the audio clip and moves to the confidence rating as soon as a response is made.  The good news is that all the audio files for the foils (files labeled N and NI) have been created, adjusted to 4s and converted to base64 in the repository already!

**Comment by evmadden** [comment]
@lancehilliard  I have run a short version of the study with all three test phases and the audio is playing perfectly and I can confirm that it is moving to the next test sentence once a keypress is detected.  Excellent work!  

I did notice one weird behaviour in the _**encoding phase**_ that I must have missed before.  I noticed that it is no longer recognising/responding when I press the spacebar upon seeing a number appear on the screen.  I can't tell if this is something I've missed in the config settings or if it's a bug.  

I also noticed that there is one sentence that isn't being read entirely and that is an error that needs fixing on _**my part**_ (it stops at a comma).  I'll update you when I get that sentence fixed and converted so it can be run through the Base64.

**Comment by lancehilliard** [comment]
@evmadden 21a91d82f540d2c0a9d3dcc64e07833bbe7ec526 temporarily adds [appsettings.74.json](https://github.com/evmadden/SDCexp1/blob/21a91d82f540d2c0a9d3dcc64e07833bbe7ec526/src/SDCode.Web/appsettings.74.json), which we will discard after we resolve this issue. With this configuration (which is nothing special - a frankenconfig - BSC.Short, but with Main's Encoding timings), my spacebar works as expected during Encoding. Please pull this file, configure your runtime to use this configuration, and let me know if your spacebar is honored when a number is displayed during Encoding. This will help us narrow down how to reproduce the problem.

If your spacebar is honored with the "74" config: what config are you able to use locally such that your spacebar is not honored?

If your spacebar is not honored with the "74" config: we will begin investigating why mine is and yours is not.

Assigning to you for testing.

**Comment by evmadden** [comment]
@lancehilliard I can confirm that my spacebar is still honoured in the 74 config but when I switch back to the AudioDevelopment config, my spacebar is no longer honoured.

**Comment by lancehilliard** [comment]
@evmadden caec347df9c4c1300f3832e9e1749df0f8f9f5fd resolves the spacebar concern. Please pull, test locally, and provide feedback.

This was happening in AudioDevelopment because NumberCheckIntervalInMilliseconds was greater than NumberDisplayThresholdInMilliseconds in that configuration. Respectively, [they were 5000/10 and are now 100/5000](https://github.com/evmadden/SDCexp1/commit/caec347df9c4c1300f3832e9e1749df0f8f9f5fd#diff-3e41f8a935320dd24c45854dd88532f85286ef00f2ea9b5479a4f1f7b63ea4d1).

**NumberCheckIntervalInMilliseconds:** interval between spacebar detection checks
**NumberDisplayThresholdInMilliseconds:** duration for which number is shown

The AudioDevelopment config wasn't showing the number long enough to arrive at the first moment when the runtime was configured to check for a spacebar press. Whoops.

Logically speaking, that first number should probably never be configured to be larger than that second number. Even in appsettings.Development.json, where Cheating Is Job One™, the first number is 1 and the second number is 10. Silly small values, but reasonable** in that the "how long to show" duration/threshold is larger than the "how often to check" interval.

Perhaps you will want to copy these same two configuration values from appsettings.Development.json into appsettings.AudioDevelopment.json, such that the encoding numbers pass instantly and automatically when you're testing locally. But I did not do that with this commit.

Rather, I copied the values from appsettings.Main.json, so that, after pulling, you can run the AudioDevelopment config locally and confidently observe your spacebar working. It is good to realize that this problem never escaped the AudioDevelopment version, as that config was what was causing the problem. The Verbal.Development config already has reasonable** values.

At any moment after your local testing has convinced you that this is fixed, feel free to copy the smaller values from the Development configuration, if you like (maybe your priority at some point in the future will be to run the AudioDevelopment encoding sessions quite quickly, just as we long have been doing in the Development config/runtime).

Assigning to you for testing.

**Comment by evmadden** [comment]
I've been able to change the values you specified above and can confirm that the spacebar press is now being recognised!  Closing this issue with comment.
